In [1]:
import pandas as pd
import os

In [2]:
#initialise process to merge related CSVs into one

ff_data = pd.read_csv("datasets\FF_Restaurants_Per_Capita_US-States.csv")
commute_data = pd.read_csv("datasets\commute_data.csv")
active_data = pd.read_csv("datasets\obese_vs_activeness.csv")
age_data = pd.read_csv(r"datasets\age_obesity.csv")

In [3]:
#data exploration
ff_data.head(5)

,State Name,state code,alpha code,Restaurants Per Capita,Number of Fast Food Restaurants,Population (2019)
0,Alabama,1.0,AL,6.3,4442,4903185
1,Alaska,2.0,AK,2.6,411,731545
2,Arizona,4.0,AZ,4.6,4388,7278717
3,Arkansas,5.0,AR,4.7,2364,3017825
4,California,6.0,CA,3.6,31473,39512223

In [4]:
#data exploration
active_data.head(5)

,State,State Code,alpha code,total gyms,per 100K residents (%),prevalance of inactivity,meets cdc requirement (%),adolescents physically active (%),Obesity,Latitude,Longitude
0,Alabama,1.0,AL,385.0,7.9,31.0,17.6,23.2,36.2,32.601011,-86.680736
1,Alaska,2.0,AK,90.0,12.2,20.3,25.6,17.9,29.5,61.302501,-158.775020
2,Arizona,4.0,AZ,318.0,4.5,23.7,25.5,22.0,29.5,34.168219,-111.930907
3,Arkansas,5.0,AR,134.0,4.4,32.5,19.3,22.7,37.1,34.751928,-92.131378
4,California,6.0,CA,3365.0,8.5,20.4,22.6,20.5,25.8,37.271875,-119.270415

In [5]:
#from the 2 observations, both ff_data and active_data can be merged through alpha code

merged_one = pd.merge(active_data, ff_data, on='alpha code', how='right')

#once merge, need to drop duplicated columns and 'District of Columnbia'
merged_one = merged_one.drop(columns=['State Name', 'state code'], index=50)

#data check
merged_one.tail(5)

,State,State Code,alpha code,total gyms,per 100K residents (%),prevalance of inactivity,meets cdc requirement (%),adolescents physically active (%),Obesity,Latitude,Longitude,Restaurants Per Capita,Number of Fast Food Restaurants,Population (2019)
45,Virginia,51.0,VA,1140.0,13.4,24.0,22.7,22.0,30.3,38.003386,-79.458786,4.3,6757,8535519
46,Washington,53.0,WA,1002.0,34.2,18.3,25.9,NaN,28.7,38.899349,-77.014567,3.1,4844,7614893
47,West Virginia,54.0,WV,137.0,7.6,29.8,17.1,26.3,39.5,38.920171,-80.181691,5.3,1408,1792147
48,Wisconsin,55.0,WI,872.0,15.0,21.4,24.7,21.5,32.0,44.786297,-89.826705,4.0,3650,5822434
49,Wyoming,56.0,WY,55.0,9.6,24.1,24.5,NaN,29.0,43.000325,-107.554567,4.1,368,578759

In [7]:
#data exploration
age_data.head(5)

,Unnamed: 0,Obesity,"$25-$49,999","$50-$74,999","$75,000 or More",Ages 18-44,Ages 45-64,Ages 65+,American Indian/Alaska Native,Asian,...,Hawaiian/Pacific Islander,High School Grad,Hispanic,"Less Than $25,000",Less Than High School,Male,Multiracial,Other Race,Some College,White
0,Alaska,29.5,32.8,26.3,31.6,27.5,33.8,27.2,29.1,0.0,...,0.0,33.7,26.9,31.2,34.1,29.9,32.7,0.0,32.0,29.2
1,Alabama,36.2,39.3,41.1,33.4,34.3,41.8,31.8,25.4,0.0,...,0.0,39.5,30.8,43.1,42.5,34.6,37.2,0.0,41.7,34.2
2,Arkansas,37.1,39.5,40.6,34.6,36.5,42.9,30.1,40.3,0.0,...,0.0,38.8,37.7,42.5,38.2,34.9,42.0,0.0,41.5,35.7
3,Arizona,29.5,33.4,31.2,25.6,26.9,36.1,26.1,48.6,0.0,...,0.0,34.2,33.8,40.3,43.4,31.0,28.7,31.7,31.7,27.5
4,California,25.8,29.0,31.1,22.0,23.3,30.3,24.2,34.5,10.9,...,0.0,31.6,33.3,34.7,35.3,26.0,24.8,26.3,30.0,22.8

In [8]:
#data exploration
commute_data.head(5)

     State                        Mode  Year Commute mode share (percent)
0  Alabama                     Bicycle  2019                        0.14%
1  Alabama                      Walked  2019                        1.23%
2  Alabama  Taxi, motorcycle, or other  2019                        0.98%
3  Alabama       Public transportation  2019                        0.42%
4  Alabama              Worked at home  2019                        3.39%

In [9]:
'''
further exploration of age_data and commute data needed
more transformation where age_data needs to be cleaned up
and commute_data['Mode'] needs to be made to columns so 
commute_data['State'] does not repeat itself
'''

pivot_commute = commute_data.pivot(index='State', columns='Mode', values='Commute mode share (percent)')
pivot_commute.reset_index(inplace=True)

#as we do not want to include District of Columbia and Puerto Rico
pivot_commute = pivot_commute.drop(pivot_commute.index[[8,39]])


#data check to ensure unwanted state removed
pivot_commute

Mode,State,Bicycle,Carpool,Drove alone,Public transportation,"Taxi, motorcycle, or other",Walked,Worked at home
0,Alabama,0.14%,8.67%,85.17%,0.42%,0.98%,1.23%,3.39%
1,Alaska,0.66%,12.00%,69.96%,0.96%,5.01%,7.07%,4.33%
2,Arizona,0.77%,10.65%,75.64%,1.68%,1.78%,1.91%,7.58%
3,Arkansas,0.15%,10.71%,82.41%,0.40%,0.88%,1.93%,3.52%
4,California,0.86%,9.83%,73.51%,5.18%,1.72%,2.56%,6.34%
5,Colorado,1.13%,8.58%,74.19%,3.19%,1.09%,2.69%,9.12%
6,Connecticut,0.35%,7.55%,78.33%,4.52%,0.87%,2.81%,5.58%
7,Delaware,0.23%,8.54%,80.66%,2.35%,0.78%,2.26%,5.16%
9,Florida,0.60%,9.14%,78.14%,1.59%,1.97%,1.57%,6.98%
10,Georgia,0.20%,9.26%,78.37%,1.98%,1.76%,1.49%,6.94%
11,Hawaii,0.58%,13.26%,69.27%,5.37%,2.20%,4.56%,4.77%
12,Idaho,0.76%,9.21%,78.29%,0.77%,0.90%,2.69%,7.38%
13,Illinois,0.57%,7.61%,72.42%,9.65%,1.30%,3.02%,5.43%
14,Indiana,0.41%,9.50%,81.63%,0.92%,0.96%,2.26%,4.31%
15,Iowa,0.34%,8.57%,80.20%,1.12%,0.84%,3.18%,5.76%
16,Kansas,0.27%,8.47%,82.71%,0.50%,0.72%,2.21%,5.12%
17,Kentucky,0.24%,9.04%,81.95%,0.99%,1.21%,2.27%,4.30%
18,Louisiana,0.37%,8.78%,82.12%,1.18%,1.50%,2.13%,3.94%
19,Maine,0.27%,9.53%,78.48%,0.64%,0.99%,3.81%,6.29%
20,Maryland,0.31%,8.69%,73.89%,8.03%,1.35%,2.21%,5.51%
21,Massachusetts,0.89%,7.28%,69.62%,10.42%,1.35%,4.99%,5.44%
22,Michigan,0.35%,8.88%,81.78%,1.40%,0.92%,2.17%,4.51%
23,Minnesota,0.68%,8.23%,77.62%,3.40%,0.99%,2.62%,6.45%
24,Mississippi,0.07%,8.94%,84.84%,0.25%,1.69%,1.09%,3.11%
25,Missouri,0.24%,8.39%,82.07%,1.15%,1.01%,2.08%,5.06%
26,Montana,1.21%,9.90%,76.17%,0.92%,1.09%,4.18%,6.53%
27,Nebraska,0.31%,8.96%,81.79%,0.81%,0.73%,2.75%,4.64%
28,Nevada,0.25%,10.62%,76.97%,3.06%,2.62%,1.59%,4.88%
29,New Hampshire,0.32%,7.83%,80.36%,0.87%,0.88%,2.42%,7.33%
30,New Jersey,0.24%,7.89%,70.96%,11.55%,1.76%,2.69%,4.92%
31,New Mexico,0.67%,9.35%,80.73%,1.05%,1.12%,2.00%,5.08%
32,New York,0.73%,6.27%,52.77%,27.72%,1.53%,6.19%,4.80%
33,North Carolina,0.16%,8.74%,80.17%,1.13%,1.32%,1.78%,6.71%
34,North Dakota,0.25%,8.49%,82.55%,0.71%,1.24%,3.16%,3.60%
35,Ohio,0.26%,8.01%,82.38%,1.50%,0.98%,2.28%,4.59%
36,Oklahoma,0.24%,9.48%,82.65%,0.43%,1.33%,1.46%,4.42%
37,Oregon,1.95%,9.47%,71.53%,4.67%,1.32%,3.78%,7.29%
38,Pennsylvania,0.45%,8.42%,75.20%,5.72%,1.17%,3.65%,5.40%
40,Rhode Island,0.27%,8.18%,79.60%,3.07%,1.09%,3.28%,4.51%
41,South Carolina,0.23%,8.64%,82.05%,0.59%,1.32%,2.05%,5.12%
42,South Dakota,0.38%,8.96%,79.75%,0.35%,1.22%,3.22%,6.11%
43,Tennessee,0.12%,8.90%,82.01%,0.62%,1.31%,1.41%,5.64%
44,Texas,0.23%,9.70%,80.14%,1.33%,1.34%,1.54%,5.71%
45,Utah,0.54%,10.36%,76.12%,2.47%,1.03%,2.05%,7.43%
46,Vermont,0.50%,8.55%,76.19%,1.64%,0.77%,5.31%,7.04%
47,Virginia,0.35%,8.99%,76.63%,4.35%,1.60%,2.32%,5.76%
48,Washington,0.87%,9.95%,70.92%,7.11%,1.15%,3.48%,6.51%
49,West Virginia,0.13%,9.04%,81.99%,0.79%,1.24%,2.90%,3.92%
50,Wisconsin,0.62%,7.99%,80.76%,1.69%,0.89%,2.96%,5.10%
51,Wyoming,1.04%,11.51%,76.91%,1.16%,0.69%,2.95%,5.73%

In [10]:
#to remove % symbols
pivot_commute=pivot_commute.replace('%','',regex=True)

In [11]:
#commute data(pivot_commute) can now be merged with merged_one
merged_two = pd.merge(merged_one, pivot_commute, on='State', how='right')

#data check
merged_two.head(5)

,State,State Code,alpha code,total gyms,per 100K residents (%),prevalance of inactivity,meets cdc requirement (%),adolescents physically active (%),Obesity,Latitude,...,Restaurants Per Capita,Number of Fast Food Restaurants,Population (2019),Bicycle,Carpool,Drove alone,Public transportation,"Taxi, motorcycle, or other",Walked,Worked at home
0,Alabama,1.0,AL,385.0,7.9,31.0,17.6,23.2,36.2,32.601011,...,6.3,4442,4903185,0.14,8.67,85.17,0.42,0.98,1.23,3.39
1,Alaska,2.0,AK,90.0,12.2,20.3,25.6,17.9,29.5,61.302501,...,2.6,411,731545,0.66,12.00,69.96,0.96,5.01,7.07,4.33
2,Arizona,4.0,AZ,318.0,4.5,23.7,25.5,22.0,29.5,34.168219,...,4.6,4388,7278717,0.77,10.65,75.64,1.68,1.78,1.91,7.58
3,Arkansas,5.0,AR,134.0,4.4,32.5,19.3,22.7,37.1,34.751928,...,4.7,2364,3017825,0.15,10.71,82.41,0.40,0.88,1.93,3.52
4,California,6.0,CA,3365.0,8.5,20.4,22.6,20.5,25.8,37.271875,...,3.6,31473,39512223,0.86,9.83,73.51,5.18,1.72,2.56,6.34

In [12]:
#As the age_data dataframe has a lot of data, needed to rearrange the columns for easier understanding
age_data.rename(columns={'Unnamed: 0':'State'}, inplace = True)

#view all column names, then rearrange according to logical order
age_data.columns

Index(['State', 'Obesity', '$25-$49,999', '$50-$74,999', '$75,000 or More',
       'Ages 18-44', 'Ages 45-64', 'Ages 65+', 'American Indian/Alaska Native',
       'Asian', 'Black', 'College Grad', 'Female', 'Hawaiian/Pacific Islander',
       'High School Grad', 'Hispanic', 'Less Than $25,000',
       'Less Than High School', 'Male', 'Multiracial', 'Other Race',
       'Some College', 'White'],
      dtype='object')

In [ ]:
# rearrange column headers according to categories sex, income level, age group, race, educational level
age_data = age_data[['State', 'Obesity','Male', 'Female','Less Than $25,000', '$25-$49,999', '$50-$74,999', '$75,000 or More',
       'Ages 18-44', 'Ages 45-64', 'Ages 65+', 'White', 'American Indian/Alaska Native',
       'Asian', 'Black', 'Hispanic', 'Multiracial', 'Hawaiian/Pacific Islander', 'Other Race', 
        'High School Grad','Less Than High School', 'College Grad','Some College']]
# to drop off District of Columbia
age_data = age_data.drop(index=7)

In [13]:
#data check
age_data

,State,Obesity,"$25-$49,999","$50-$74,999","$75,000 or More",Ages 18-44,Ages 45-64,Ages 65+,American Indian/Alaska Native,Asian,...,Hawaiian/Pacific Islander,High School Grad,Hispanic,"Less Than $25,000",Less Than High School,Male,Multiracial,Other Race,Some College,White
0,Alaska,29.5,32.8,26.3,31.6,27.5,33.8,27.2,29.1,0.0,...,0.0,33.7,26.9,31.2,34.1,29.9,32.7,0.0,32.0,29.2
1,Alabama,36.2,39.3,41.1,33.4,34.3,41.8,31.8,25.4,0.0,...,0.0,39.5,30.8,43.1,42.5,34.6,37.2,0.0,41.7,34.2
2,Arkansas,37.1,39.5,40.6,34.6,36.5,42.9,30.1,40.3,0.0,...,0.0,38.8,37.7,42.5,38.2,34.9,42.0,0.0,41.5,35.7
3,Arizona,29.5,33.4,31.2,25.6,26.9,36.1,26.1,48.6,0.0,...,0.0,34.2,33.8,40.3,43.4,31.0,28.7,31.7,31.7,27.5
4,California,25.8,29.0,31.1,22.0,23.3,30.3,24.2,34.5,10.9,...,0.0,31.6,33.3,34.7,35.3,26.0,24.8,26.3,30.0,22.8
5,Colorado,22.9,24.8,23.3,23.4,20.0,28.0,21.8,24.4,0.0,...,0.0,28.7,29.8,29.7,32.2,21.8,32.2,30.3,28.1,21.3
6,Connecticut,27.4,34.4,31.6,26.4,23.9,32.3,26.3,0.0,10.9,...,0.0,33.5,31.1,34.1,33.4,28.4,23.9,34.4,33.2,26.1
7,District of Columbia,24.7,34.5,27.1,16.4,21.3,31.6,25.2,0.0,0.0,...,0.0,37.1,30.1,40.5,39.6,21.2,23.6,0.0,37.4,12.3
8,Delaware,33.5,35.6,35.3,33.8,29.7,39.0,32.5,0.0,0.0,...,0.0,37.9,33.8,40.1,45.7,33.6,51.2,0.0,37.3,32.4
9,Florida,30.7,33.2,35.7,28.7,28.1,36.2,27.8,24.4,0.0,...,0.0,33.6,33.7,36.6,38.6,31.1,37.7,34.1,33.4,28.0
10,Georgia,32.5,35.3,37.0,29.6,29.9,37.6,29.6,17.5,12.1,...,0.0,38.7,30.2,40.9,37.9,31.6,32.1,0.0,36.4,29.7
11,Hawaii,24.9,25.1,26.9,23.5,26.2,28.7,17.4,0.0,17.5,...,45.2,33.7,34.0,29.7,27.1,26.8,35.5,0.0,24.7,18.2
12,Iowa,35.3,42.2,37.4,34.3,32.5,40.2,34.0,0.0,25.4,...,0.0,40.8,37.4,43.9,42.8,36.0,39.8,0.0,40.1,35.0
13,Idaho,28.4,32.8,30.0,27.4,24.2,34.0,29.0,0.0,0.0,...,0.0,28.2,32.1,36.1,37.9,29.7,0.0,0.0,36.4,27.9
14,Illinois,31.8,31.3,35.5,29.7,28.3,36.0,32.5,0.0,10.2,...,0.0,35.8,36.7,40.9,39.5,30.1,28.9,0.0,39.1,30.6
15,Indiana,34.1,35.6,39.9,34.6,31.2,39.0,32.6,57.0,0.0,...,0.0,38.4,39.3,38.6,36.4,33.9,38.0,33.3,37.4,33.6
16,Kansas,34.4,36.4,38.1,33.4,32.0,40.1,31.0,43.5,16.4,...,0.0,40.8,38.0,43.1,35.0,33.3,38.1,0.0,40.1,33.8
17,Kentucky,36.6,42.4,42.0,35.3,34.1,43.8,30.8,0.0,0.0,...,0.0,41.1,34.1,44.0,41.1,36.4,29.0,0.0,39.2,36.8
18,Louisiana,36.8,40.8,40.5,34.3,34.7,42.9,31.8,39.8,0.0,...,0.0,42.0,29.3,41.6,34.9,34.1,37.3,0.0,41.1,33.0
19,Massachusetts,25.7,28.2,28.6,26.4,22.6,29.5,25.9,0.0,6.5,...,0.0,32.7,30.2,32.9,30.0,27.0,40.0,30.3,31.8,26.2
20,Maryland,30.9,37.6,32.4,30.9,28.4,36.1,27.9,41.8,12.8,...,0.0,34.7,30.8,37.8,37.3,28.6,31.2,36.9,38.4,28.8
21,Maine,30.4,33.7,30.6,27.2,28.8,34.2,27.2,42.3,0.0,...,0.0,35.4,19.9,37.5,33.8,31.5,35.5,0.0,34.7,30.2
22,Michigan,33.0,36.4,34.6,31.9,29.1,38.3,32.3,32.6,0.0,...,0.0,37.3,35.5,41.8,37.5,31.4,34.0,31.5,39.2,32.4
23,Minnesota,30.1,34.0,33.1,29.0,26.8,34.5,30.0,50.2,20.1,...,0.0,36.3,32.8,38.1,36.0,32.4,35.2,0.0,34.4,30.0
24,Missouri,35.0,39.9,38.7,33.5,33.4,39.7,31.3,52.5,0.0,...,0.0,38.3,50.9,41.0,38.0,34.4,40.7,0.0,42.0,33.1
25,Mississippi,39.5,39.9,40.7,38.6,38.5,45.2,32.8,0.0,0.0,...,0.0,43.4,0.0,46.9,39.4,36.1,0.0,0.0,43.1,36.3
26,Montana,26.9,29.7,31.5,26.6,24.0,32.7,24.1,41.4,0.0,...,0.0,30.1,23.7,32.7,28.6,27.8,31.2,0.0,30.7,25.9
27,North Carolina,33.0,39.7,37.5,31.4,28.4,42.4,27.6,58.6,0.0,...,0.0,36.3,30.6,37.5,39.3,32.1,36.6,0.0,41.6,29.4
28,North Dakota,35.1,38.8,37.6,36.3,32.9,39.4,34.3,44.8,0.0,...,0.0,40.6,41.0,41.5,36.7,36.0,37.0,0.0,40.0,34.9
29,Nebraska,34.1,38.7,39.0,32.6,29.9,41.5,32.4,43.2,0.0,...,0.0,38.7,34.3,40.8,41.3,34.5,37.4,0.0,38.8,33.9
30,New Hampshire,29.6,33.7,29.4,27.6,28.3,31.8,28.3,0.0,0.0,...,0.0,35.9,0.0,40.8,43.2,31.1,28.9,0.0,32.6,30.0
31,New Jersey,25.6,30.7,31.9,25.0,22.8,28.9,25.8,0.0,0.0,...,0.0,34.0,26.2,35.0,29.9,25.8,0.0,0.0,31.6,26.1
32,New Mexico,32.3,33.6,38.1,28.8,33.2,36.5,24.9,41.6,0.0,...,0.0,35.5,37.8,37.6,40.2,31.2,0.0,0.0,34.3,25.5
33,Nevada,29.5,35.9,33.5,29.4,26.6,34.5,28.0,0.0,0.0,...,0.0,28.4,33.5,35.2,35.3,29.7,20.2,0.0,37.4,27.6
34,New York,27.6,32.1,31.9,25.7,25.0,31.7,27.0,32.1,12.4,...,34.9,33.6,31.4,33.0,32.8,27.9,32.3,24.0,31.1,27.4
35,Ohio,34.0,35.4,38.1,34.8,30.8,39.1,32.7,0.0,0.0,...,0.0,39.0,43.3,40.2,34.1,33.8,36.5,0.0,37.9,34.0
36,Oklahoma,34.8,38.4,36.9,35.3,33.6,40.1,29.4,38.0,0.0,...,0.0,37.3,32.5,37.3,35.8,32.8,35.5,0.0,38.0,34.6
37,Oregon,29.9,32.8,33.5,28.6,26.1,36.7,27.9,43.3,0.0,...,0.0,34.7,34.8,37.3,39.1,29.2,31.8,0.0,34.4,29.6
38,Pennsylvania,30.9,35.5,34.5,30.8,27.4,37.3,28.3,0.0,0.0,...,0.0,35.2,34.9,34.4,26.6,30.9,18.6,0.0,39.7,29.9
39,Rhode Island,27.7,32.0,25.5,26.1,24.2,33.0,26.6,0.0,0.0,...,0.0,32.5,32.2,34.9,36.8,28.4,34.1,28.5,30.2,26.2
40,South Carolina,34.3,39.7,35.4,30.5,31.5,40.0,31.5,43.7,0.0,...,0.0,39.0,27.7,41.3,39.5,32.3,27.3,29.0,38.6,32.1
41,South Dakota,30.1,31.3,31.0,30.5,25.9,34.6,31.8,47.5,0.0,...,0.0,31.0,26.6,41.8,36.5,31.1,42.6,0.0,35.7,29.1
42,Tennessee,34.4,34.7,41.0,31.9,31.5,40.5,30.7,0.0,0.0,...,0.0,38.9,33.9,40.5,35.1,33.5,45.8,0.0,37.4,33.3
43,Texas,34.8,38.7,43.2,32.2,32.4,38.2,35.3,54.1,10.0,...,0.0,42.3,38.6,39.7,40.1,33.5,22.7,25.0,38.2,33.1
44,Utah,27.7,32.3,32.3,27.7,24.5,33.5,29.2,40.6,15.3,...,0.0,34.1,30.0,33.0,32.0,28.7,40.7,0.0,31.2,27.1
45,Virginia,30.3,34.8,37.5,28.4,26.5,36.4,29.2,29.4,13.4,...,0.0,36.3,27.7,41.4,36.8,30.4,37.1,0.0,36.9,29.3
46,Vermont,27.5,31.5,32.9,23.5,24.8,32.3,25.4,37.6,0.0,...,0.0,37.8,0.0,35.7,34.6,27.7,20.4,0.0,30.4,28.0
47,Washington,28.7,34.7,33.3,27.9,25.8,33.9,26.9,30.2,9.8,...,35.8,35.9,36.8,34.4,33.5,29.4,32.6,33.5,35.3,29.4
48,Wisconsin,32.0,35.6,35.5,28.9,31.6,34.9,28.4,46.7,0.0,...,0.0,38.4,40.3,37.0,32.8,31.0,33.8,38.7,35.3,31.4
49,West Virginia,39.5,40.0,43.8,40.0,37.9,45.4,34.0,0.0,0.0,...,0.0,42.3,0.0,45.9,44.8,40.6,34.7,0.0,42.0,39.9
50,Wyoming,29.0,29.4,34.1,29.3,24.9,36.6,26.4,0.0,0.0,...,0.0,29.7,33.9,37.7,32.9,30.2,0.0,0.0,37.4,28.4

In [16]:
'''
The following is performed to check the data types so it can be transformed late
We can then see Bicycle,Carpool, Drove alone, Public transportation, 
Taxi, motorcycle, or other, Walked, Worked at home are all 
object type which later need to be transformed into float to be used for calculations
'''

merged_two.dtypes

State                                 object
State Code                           float64
alpha code                            object
total gyms                           float64
per 100K residents (%)               float64
prevalance of inactivity             float64
meets cdc requirement (%)            float64
adolescents physically active (%)    float64
Obesity                              float64
Latitude                             float64
Longitude                            float64
Restaurants Per Capita               float64
Number of Fast Food Restaurants        int64
Population (2019)                      int64
Bicycle                               object
Carpool                               object
Drove alone                           object
Public transportation                 object
Taxi, motorcycle, or other            object
Walked                                object
Worked at home                        object
dtype: object

In [18]:
'''
to check the same for age_data 
We can see that age_data are of float data type which 
is what we need 
'''
age_data.dtypes

State                             object
Obesity                          float64
$25-$49,999                      float64
$50-$74,999                      float64
$75,000 or More                  float64
Ages 18-44                       float64
Ages 45-64                       float64
Ages 65+                         float64
American Indian/Alaska Native    float64
Asian                            float64
Black                            float64
College Grad                     float64
Female                           float64
Hawaiian/Pacific Islander        float64
High School Grad                 float64
Hispanic                         float64
Less Than $25,000                float64
Less Than High School            float64
Male                             float64
Multiracial                      float64
Other Race                       float64
Some College                     float64
White                            float64
dtype: object

In [19]:
'''
As merged_two dataframe and age_data dataframe had lots of columns and data to work with, I will not merge both of them.
Time to export the data so it can be used for the visualisations
'''

merged_two.to_csv('datasets\cleaned\combined_us_data.csv',index = False, header=True)
age_data.to_csv('datasets\cleaned\demographics_data.csv', index=False, header=True)

'''
Further data transformation will be continued using Power BI Power Query Editor
'''

'\nFurther data transformation will be continued using Power BI Power Query Editor\n'